<a href="https://colab.research.google.com/github/olubunmikufoniyi/olubunmikufoniyi/blob/main/Matrix_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
second_matrix = np.array([[4, 5, 6], [7, 8, 9]])
print(first_matrix)
print(second_matrix)


[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]


In [ ]:
np.mean(first_matrix)


3.5

In [11]:
np.mean(second_matrix)
print(second_matrix)
np.mean(first_matrix)
print(first_matrix)
np.median(second_matrix)
print(second_matrix)
np.median(first_matrix)
print(first_matrix)

[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [14]:
from scipy import stats
stats.mode(first_matrix)


ModeResult(mode=array([1, 2, 3]), count=array([1, 1, 1]))

In [16]:
np.add((first_matrix), second_matrix)

array([[ 5,  7,  9],
       [11, 13, 15]])

In [17]:
np.subtract((first_matrix), second_matrix)

array([[-3, -3, -3],
       [-3, -3, -3]])

In [21]:
np.multiply(first_matrix, second_matrix)

array([[ 4, 10, 18],
       [28, 40, 54]])

In [22]:
np.multiply(first_matrix, 5)

array([[ 5, 10, 15],
       [20, 25, 30]])

In [23]:
np.multiply(second_matrix, 5)

array([[20, 25, 30],
       [35, 40, 45]])

In [24]:
first_matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
second_matrix.T

array([[4, 7],
       [5, 8],
       [6, 9]])